[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://vagasdaqui.cyclic.cloud"
      Access-Control-Allow-Methods = "POST, OPTIONS"
      Access-Control-Allow-Headers = "Content-Type"

